In [57]:
import networkx as nx
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
from operator import itemgetter
import powerlaw
from networkx.drawing.nx_agraph import graphviz_layout
import pickle
from statistics import mean, stdev
import seaborn as sns

In [58]:
from net_analysis import *

In [81]:
path_edges = "../Dataset SuperUsers/edges.csv"
path_nodes = "../Dataset SuperUsers/nodes.csv"
path_all = "../Dataset SuperUsers/questions_2020_2022.csv"
edges = "../Dataset SuperUsers/edges_10K.csv"

In [82]:
G = nx.read_edgelist(edges, comments = "S", delimiter = ",", data=(("Count", int),))

In [83]:
G.number_of_nodes()

4147

In [76]:
print(nx.info(G))

Name:
Type: Graph
Number of nodes: 4147
Number of edges: 63400
Average degree:  30.5763

In [30]:
df_all

,Tags,User_Name,Title,View_count,Down_vote_count,Up_vote_count,Answer_count,Score,Creation_date,Question_id,Question_link,Is_Answered
0,macos|-|python|-|zsh|-|compression|-|tar|-|,Saaru Lindest&#248;kke,Why are tar.xz files 15x smaller when using Py...,57933,0,242,3,242,242,1615657068,1633073,https://superuser.com/questions/1633073/why-ar...
1,crash|-|,Stuntddude,Why does my PC crash only when my cat is nearby?,24585,8,150,11,142,142,1613416737,1626284,https://superuser.com/questions/1626284/why-do...
2,windows-10|-|memory|-|docker|-|resources|-|,CiaranWelsh,How can I reduce the consumption of the `vmmem...,225274,0,116,11,116,116,1591697218,1559170,https://superuser.com/questions/1559170/how-ca...
3,windows|-|uninstall|-|,Anne Maier,What is the best way to remove 100% of a softw...,13317,1,95,13,94,94,1606380846,1605207,https://superuser.com/questions/1605207/what-i...
4,motherboard|-|,MechMK1,How do modern motherboards differ from each ot...,11845,2,92,3,90,90,1604851644,1600547,https://superuser.com/questions/1600547/how-do...
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,linux|-|windows|-|windows-subsystem-for-linux|...,Sean,dual Kali linux instances windows wsl2,65,0,0,1,0,0,1651520993,1719099,https://superuser.com/questions/1719099/dual-k...
49996,microsoft-excel|-|,Jeff,Add cells then subtract 1 if there is a date i...,42,0,0,1,0,0,1651522084,1719100,https://superuser.com/questions/1719100/add-ce...
49997,microsoft-excel|-|worksheet-function|-|time|-|,Mira,How to calculate how many days have passed bas...,12,0,0,1,0,0,1651523775,1719103,https://superuser.com/questions/1719103/how-to...
49998,linux|-|ubuntu|-|mount|-|windows-subsystem-for...,cclloyd,NFS Permission Denied when mounting from WSL,438,0,0,1,0,0,1651524070,1719105,https://superuser.com/questions/1719105/nfs-pe...
49999,microsoft-excel|-|spreadsheet|-|vlookup|-|,stckexhnge57,Lookup the 1st or nth appearance of value betw...,40,0,0,1,0,0,1651524648,1719106,https://superuser.com/questions/1719106/lookup...

In [12]:
df_nodes

                       Id
0                 corsair
1             playstation
2         total-commander
3         process-monitor
4             gtk-windows
...                   ...
4142          android-x86
4143   desktop-management
4144  microsoft-word-2016
4145               handle
4146     wireless-headset

[4147 rows x 1 columns]

In [13]:
df_edges

                     Source                Target  Count
0                     macos                python     14
1                     macos                   zsh     57
2                     macos           compression      3
3                     macos                   tar      3
4                     macos                 crash      3
...                     ...                   ...    ...
63395          blob-storage                azcopy      1
63396             raspberry                   apm      1
63397          input-method  chinese-input-method      1
63398          input-method             ime-quick      1
63399  chinese-input-method             ime-quick      1

[63400 rows x 3 columns]

In [16]:
df_edges.value_counts()

Source     Target               Count
.net-core  api                  1        1
router     cisco-packet-tracer  1        1
           clone                1        1
           cluster              1        1
           coaxial              2        1
                                        ..
html       script               2        1
           search-engines       1        1
           sendmail             1        1
           sftp                 1        1
zsh        xquartz              1        1
Length: 63400, dtype: int64

In [26]:
df_edges['Source'].unique()

array(['macos', 'python', 'zsh', ..., 'raspberry', 'input-method',
       'chinese-input-method'], dtype=object)